sudo: required
dist: trusty


language: python
cache: pip

addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
    - postgresql
env:
  - CXX=g++-4.8


python:
  - "2.7"
  - "3.4"

node_js:
  - "6"

before_install:
  - pushd frontend
  - nvm install 6
  # add node_modules/.bin to the path so that ember command is detected
  - export PATH=./node_modules/.bin:$PATH
  - npm install -g npm@5.3.0
  - npm config set spin false
  - node -v
  - npm -v
  - npm cache verify
  - npm install -g bower
  - bower --version
  - popd


install:
  # Frontend stuff
  - pushd frontend
  - npm run
  - npm install
  - bower install
  - popd
  # API server stuff  
  - pip install -r requirements.txt
  - git clone https://github.com/fossasia/pslab-python.git
  - pushd pslab-python
  - sudo python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then cp -R /usr/local/lib/python2.7/dist-packages/PSL /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then cp -R /usr/local/lib/python2.7/dist-packages/PSL /home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/; fi
  - popd

before_script:
  - psql -c 'create database psl_db;' -U postgres
  - export DATABASE_URL=postgres:///psl_db
#  - psql -c "CREATE USER psl;" -U postgres

script: nosetests

after_success:
  - pushd frontend
  - bash surge_deploy.sh
  - popd
  
after_failure: cat /home/travis/.npm/_logs/*.log
  
